# This is a basic workflow that is manually triggered

name: Downloading workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Basic Workflow Step
        #if: ${{ false }}
        run: |
          pwd
          ls -lah
      - name: Create Time Stamp
        if: ${{ false }}
        run: |
          echo date > timestamp.txt    
      - name: Upload Time Stamp
        if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt 

      - name: Ext Upload Time Stamp
        if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: Time Stamp Ext
          path: timestamp.txt
