# This is a basic workflow that is manually triggered

name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build Type'
        # Default value if no value is explicitly provided
        default: 'Deployment'
        # Input has to be provided for the workflow to run
#         required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if the artifact is from a different repo
        # Required, if the repo is private a Personal Access Token with `repo` scope is needed
         github_token: ${{secrets.GITHUB_TOKEN}}
         # Optional, workflow file name or ID
         # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
         workflow: composite-workflow.yml
         name: timestamp
      - name: Extract Last Run Time
        run: |
          lastRun=$(cat timestamp.txt)
          echo "Last Run: $lastRun"
          #ls -R          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |  
          echo "Building..."
          pwd
          ls -lah
          ./scripts/deploy.sh
      - name: Sign
        run: |          
          echo "Signing..."
      - name: Upload
        run: |          
          echo "Uploading..."  
          currentRun=$(cat timestamp.txt)
          echo "Current Run: $currentRun"
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.txt
      - name: Upload Time Stamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt   
#   release-project:
#     name: Release Project
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download Artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: timestamp
#       - name: Test Download
#         run: ls -R          
